// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using PRN232_GradingSystem_Repositories.Models;

namespace PRN232_GradingSystem_Repositories.DBContext;

public partial class PRN232_GradingSystem_APIContext : DbContext
{
    public PRN232_GradingSystem_APIContext(DbContextOptions<PRN232_GradingSystem_APIContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Exam> Exams { get; set; }

    public virtual DbSet<Grade> Grades { get; set; }

    public virtual DbSet<Gradedetail> Gradedetails { get; set; }

    public virtual DbSet<Group> Groups { get; set; }

    public virtual DbSet<GroupStudent> GroupStudents { get; set; }

    public virtual DbSet<Semester> Semesters { get; set; }

    public virtual DbSet<SemesterSubject> SemesterSubjects { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<Subject> Subjects { get; set; }

    public virtual DbSet<Submission> Submissions { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Exam>(entity =>
        {
            entity.HasKey(e => e.Examid).HasName("exam_pkey");

            entity.ToTable("exam");

            entity.Property(e => e.Examid).HasColumnName("examid");
            entity.Property(e => e.Createat)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("createat");
            entity.Property(e => e.Examdate).HasColumnName("examdate");
            entity.Property(e => e.Examname)
                .HasMaxLength(255)
                .HasColumnName("examname");
            entity.Property(e => e.Semesterid).HasColumnName("semesterid");
            entity.Property(e => e.Subjectid).HasColumnName("subjectid");

            entity.HasOne(d => d.Semester).WithMany(p => p.Exams)
                .HasForeignKey(d => d.Semesterid)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("exam_semesterid_fkey");

            entity.HasOne(d => d.Subject).WithMany(p => p.Exams)
                .HasForeignKey(d => d.Subjectid)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("exam_subjectid_fkey");
        });

        modelBuilder.Entity<Grade>(entity =>
        {
            entity.HasKey(e => e.Gradeid).HasName("grade_pkey");

            entity.ToTable("grade");

            entity.Property(e => e.Gradeid).HasColumnName("gradeid");
            entity.Property(e => e.Createat)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("createat");
            entity.Property(e => e.Marker).HasColumnName("marker");
            entity.Property(e => e.Q1)
                .HasPrecision(5, 2)
                .HasColumnName("q1");
            entity.Property(e => e.Q2)
                .HasPrecision(5, 2)
                .HasColumnName("q2");
            entity.Property(e => e.Q3)
                .HasPrecision(5, 2)
                .HasColumnName("q3");
            entity.Property(e => e.Q4)
                .HasPrecision(5, 2)
                .HasColumnName("q4");
            entity.Property(e => e.Q5)
                .HasPrecision(5, 2)
                .HasColumnName("q5");
            entity.Property(e => e.Q6)
                .HasPrecision(5, 2)
                .HasColumnName("q6");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.Submissionid).HasColumnName("submissionid");
            entity.Property(e => e.Totalscore)
                .HasPrecision(6, 2)
                .HasColumnName("totalscore");
            entity.Property(e => e.Updateat).HasColumnName("updateat");

            entity.HasOne(d => d.MarkerNavigation).WithMany(p => p.Grades)
                .HasForeignKey(d => d.Marker)
                .HasConstraintName("grade_marker_fkey");

            entity.HasOne(d => d.Submission).WithMany(p => p.Grades)
                .HasForeignKey(d => d.Submissionid)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("grade_submissionid_fkey");
        });

        modelBuilder.Entity<Gradedetail>(entity =>
        {
            entity.HasKey(e => e.Gradedetailid).HasName("gradedetail_pkey");

            entity.ToTable("gradedetail");

            entity.Property(e => e.Gradedetailid).HasColumnName("gradedetailid");
            entity.Property(e => e.Createat)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("createat");
            entity.Property(e => e.Gradeid).HasColumnName("gradeid");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.Point)
                .HasPrecision(5, 2)
                .HasColumnName("point");
            entity.Property(e => e.Qcode)
                .HasMaxLength(50)
                .HasColumnName("qcode");
            entity.Property(e => e.Subcode)
                .HasMaxLength(255)
                .HasColumnName("subcode");
            entity.Property(e => e.Updateat).HasColumnName("updateat");

            entity.HasOne(d => d.Grade).WithMany(p => p.Gradedetails)
                .HasForeignKey(d => d.Gradeid)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("gradedetail_gradeid_fkey");
        });

        modelBuilder.Entity<Group>(entity =>
        {
            entity.HasKey(e => e.Groupid).HasName("Group_pkey");

            entity.ToTable("Group");

            entity.Property(e => e.Groupid).HasColumnName("groupid");
            entity.Property(e => e.Createat)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("createat");
            entity.Property(e => e.Createby).HasColumnName("createby");
            entity.Property(e => e.Groupname)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("groupname");
            entity.Property(e => e.Semesterid).HasColumnName("semesterid");
            entity.Property(e => e.Updateat).HasColumnName("updateat");
            entity.Property(e => e.Updateby).HasColumnName("updateby");

            entity.HasOne(d => d.CreatebyNavigation).WithMany(p => p.GroupCreatebyNavigations)
                .HasForeignKey(d => d.Createby)
                .HasConstraintName("Group_createby_fkey");

            entity.HasOne(d => d.Semester).WithMany(p => p.Groups)
                .HasForeignKey(d => d.Semesterid)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("Group_semesterid_fkey");

            entity.HasOne(d => d.UpdatebyNavigation).WithMany(p => p.GroupUpdatebyNavigations)
                .HasForeignKey(d => d.Updateby)
                .HasConstraintName("Group_updateby_fkey");
        });

        modelBuilder.Entity<GroupStudent>(entity =>
        {
            entity.HasKey(e => new { e.Groupid, e.Studentid }).HasName("group_student_pkey");

            entity.ToTable("group_student");

            entity.Property(e => e.Groupid).HasColumnName("groupid");
            entity.Property(e => e.Studentid).HasColumnName("studentid");
            entity.Property(e => e.Createat)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("createat");

            entity.HasOne(d => d.Group).WithMany(p => p.GroupStudents)
                .HasForeignKey(d => d.Groupid)
                .HasConstraintName("group_student_groupid_fkey");

            entity.HasOne(d => d.Student).WithMany(p => p.GroupStudents)
                .HasForeignKey(d => d.Studentid)
                .HasConstraintName("group_student_studentid_fkey");
        });

        modelBuilder.Entity<Semester>(entity =>
        {
            entity.HasKey(e => e.Semesterid).HasName("semester_pkey");

            entity.ToTable("semester");

            entity.Property(e => e.Semesterid).HasColumnName("semesterid");
            entity.Property(e => e.Createat)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("createat");
            entity.Property(e => e.Createby).HasColumnName("createby");
            entity.Property(e => e.Enddate).HasColumnName("enddate");
            entity.Property(e => e.Isactive)
                .HasDefaultValue(true)
                .HasColumnName("isactive");
            entity.Property(e => e.Semestercode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("semestercode");
            entity.Property(e => e.Startdate).HasColumnName("startdate");
            entity.Property(e => e.Updateat).HasColumnName("updateat");
            entity.Property(e => e.Updateby).HasColumnName("updateby");

            entity.HasOne(d => d.CreatebyNavigation).WithMany(p => p.SemesterCreatebyNavigations)
                .HasForeignKey(d => d.Createby)
                .HasConstraintName("semester_createby_fkey");

            entity.HasOne(d => d.UpdatebyNavigation).WithMany(p => p.SemesterUpdatebyNavigations)
                .HasForeignKey(d => d.Updateby)
                .HasConstraintName("semester_updateby_fkey");
        });

        modelBuilder.Entity<SemesterSubject>(entity =>
        {
            entity.HasKey(e => new { e.Semesterid, e.Subjectid }).HasName("semester_subject_pkey");

            entity.ToTable("semester_subject");

            entity.Property(e => e.Semesterid).HasColumnName("semesterid");
            entity.Property(e => e.Subjectid).HasColumnName("subjectid");
            entity.Property(e => e.Createat)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("createat");

            entity.HasOne(d => d.Semester).WithMany(p => p.SemesterSubjects)
                .HasForeignKey(d => d.Semesterid)
                .HasConstraintName("semester_subject_semesterid_fkey");

            entity.HasOne(d => d.Subject).WithMany(p => p.SemesterSubjects)
                .HasForeignKey(d => d.Subjectid)
                .HasConstraintName("semester_subject_subjectid_fkey");
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.Studentid).HasName("student_pkey");

            entity.ToTable("student");

            entity.Property(e => e.Studentid).HasColumnName("studentid");
            entity.Property(e => e.Createat)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("createat");
            entity.Property(e => e.Isactive)
                .HasDefaultValue(true)
                .HasColumnName("isactive");
            entity.Property(e => e.Studentfullname)
                .HasMaxLength(255)
                .HasColumnName("studentfullname");
            entity.Property(e => e.Studentroll)
                .HasMaxLength(50)
                .HasColumnName("studentroll");
        });

        modelBuilder.Entity<Subject>(entity =>
        {
            entity.HasKey(e => e.Subjectid).HasName("subject_pkey");

            entity.ToTable("subject");

            entity.Property(e => e.Subjectid).HasColumnName("subjectid");
            entity.Property(e => e.Createat)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("createat");
            entity.Property(e => e.Subjectname)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("subjectname");
        });

        modelBuilder.Entity<Submission>(entity =>
        {
            entity.HasKey(e => e.Submissionid).HasName("submission_pkey");

            entity.ToTable("submission");

            entity.Property(e => e.Submissionid).HasColumnName("submissionid");
            entity.Property(e => e.Comment).HasColumnName("comment");
            entity.Property(e => e.Createat)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("createat");
            entity.Property(e => e.Examid).HasColumnName("examid");
            entity.Property(e => e.Fileurl)
                .HasMaxLength(255)
                .HasColumnName("fileurl");
            entity.Property(e => e.Solution).HasColumnName("solution");
            entity.Property(e => e.Studentid).HasColumnName("studentid");
            entity.Property(e => e.Updateat).HasColumnName("updateat");

            entity.HasOne(d => d.Exam).WithMany(p => p.Submissions)
                .HasForeignKey(d => d.Examid)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("submission_examid_fkey");

            entity.HasOne(d => d.Student).WithMany(p => p.Submissions)
                .HasForeignKey(d => d.Studentid)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("submission_studentid_fkey");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Userid).HasName("User_pkey");

            entity.ToTable("User");

            entity.Property(e => e.Userid).HasColumnName("userid");
            entity.Property(e => e.Createat)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("createat");
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .HasColumnName("email");
            entity.Property(e => e.Isactive)
                .HasDefaultValue(true)
                .HasColumnName("isactive");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasColumnName("password");
            entity.Property(e => e.Refreshtoken)
                .HasMaxLength(255)
                .HasColumnName("refreshtoken");
            entity.Property(e => e.Refreshtokenexpirytime).HasColumnName("refreshtokenexpirytime");
            entity.Property(e => e.Role)
                .HasMaxLength(50)
                .HasColumnName("role");
            entity.Property(e => e.Salt)
                .IsRequired()
                .HasColumnName("salt");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("username");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}