// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232_GradingSystem_Repositories.Models;

public partial class Gradedetail
{
    public int Gradedetailid { get; set; }

    public int? Gradeid { get; set; }

    public string Qcode { get; set; }

    public string Subcode { get; set; }

    public decimal? Point { get; set; }

    public string Note { get; set; }

    public DateTime? Createat { get; set; }

    public DateTime? Updateat { get; set; }

    public virtual Grade Grade { get; set; }
}