// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232_GradingSystem_Repositories.Models;

public partial class Grade
{
    public int Gradeid { get; set; }

    public int? Submissionid { get; set; }

    public decimal? Q1 { get; set; }

    public decimal? Q2 { get; set; }

    public decimal? Q3 { get; set; }

    public decimal? Q4 { get; set; }

    public decimal? Q5 { get; set; }

    public decimal? Q6 { get; set; }

    public decimal? Totalscore { get; set; }

    public string Status { get; set; }

    public DateTime? Createat { get; set; }

    public DateTime? Updateat { get; set; }

    public int? Marker { get; set; }

    public virtual ICollection<Gradedetail> Gradedetails { get; set; } = new List<Gradedetail>();

    public virtual User MarkerNavigation { get; set; }

    public virtual Submission Submission { get; set; }
}