// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232_GradingSystem_Repositories.Models;

public partial class Group
{
    public int Groupid { get; set; }

    public string Groupname { get; set; }

    public int? Semesterid { get; set; }

    public DateTime? Createat { get; set; }

    public DateTime? Updateat { get; set; }

    public int? Createby { get; set; }

    public int? Updateby { get; set; }

    public virtual User CreatebyNavigation { get; set; }

    public virtual ICollection<GroupStudent> GroupStudents { get; set; } = new List<GroupStudent>();

    public virtual Semester Semester { get; set; }

    public virtual User UpdatebyNavigation { get; set; }
}