// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232_GradingSystem_Repositories.Models;

public partial class GroupStudent
{
    public int Groupid { get; set; }

    public int Studentid { get; set; }

    public DateTime? Createat { get; set; }

    public virtual Group Group { get; set; }

    public virtual Student Student { get; set; }
}