// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232_GradingSystem_Repositories.Models;

public partial class Semester
{
    public int Semesterid { get; set; }

    public string Semestercode { get; set; }

    public DateTime? Startdate { get; set; }

    public DateTime? Enddate { get; set; }

    public bool? Isactive { get; set; }

    public DateTime? Createat { get; set; }

    public DateTime? Updateat { get; set; }

    public int? Createby { get; set; }

    public int? Updateby { get; set; }

    public virtual User CreatebyNavigation { get; set; }

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    public virtual ICollection<Group> Groups { get; set; } = new List<Group>();

    public virtual ICollection<SemesterSubject> SemesterSubjects { get; set; } = new List<SemesterSubject>();

    public virtual User UpdatebyNavigation { get; set; }
}