// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232_GradingSystem_Repositories.Models;

public partial class SemesterSubject
{
    public int Semesterid { get; set; }

    public int Subjectid { get; set; }

    public DateTime? Createat { get; set; }

    public virtual Semester Semester { get; set; }

    public virtual Subject Subject { get; set; }
}