// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232_GradingSystem_Repositories.Models;

public partial class Student
{
    public int Studentid { get; set; }

    public string Studentfullname { get; set; }

    public string Studentroll { get; set; }

    public bool? Isactive { get; set; }

    public DateTime? Createat { get; set; }

    public virtual ICollection<GroupStudent> GroupStudents { get; set; } = new List<GroupStudent>();

    public virtual ICollection<Submission> Submissions { get; set; } = new List<Submission>();
}