// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232_GradingSystem_Repositories.Models;

public partial class Submission
{
    public int Submissionid { get; set; }

    public int? Examid { get; set; }

    public int? Studentid { get; set; }

    public string Solution { get; set; }

    public string Comment { get; set; }

    public string Fileurl { get; set; }

    public DateTime? Createat { get; set; }

    public DateTime? Updateat { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual ICollection<Grade> Grades { get; set; } = new List<Grade>();

    public virtual Student Student { get; set; }
}