// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232_GradingSystem_Repositories.Models;

public partial class User
{
    public int Userid { get; set; }

    public string Email { get; set; }

    public string Username { get; set; }

    public byte[] Password { get; set; }

    public byte[] Salt { get; set; }

    public string Role { get; set; }

    public string Refreshtoken { get; set; }

    public DateTime? Refreshtokenexpirytime { get; set; }

    public bool? Isactive { get; set; }

    public DateTime? Createat { get; set; }

    public virtual ICollection<Grade> Grades { get; set; } = new List<Grade>();

    public virtual ICollection<Group> GroupCreatebyNavigations { get; set; } = new List<Group>();

    public virtual ICollection<Group> GroupUpdatebyNavigations { get; set; } = new List<Group>();

    public virtual ICollection<Semester> SemesterCreatebyNavigations { get; set; } = new List<Semester>();

    public virtual ICollection<Semester> SemesterUpdatebyNavigations { get; set; } = new List<Semester>();
}